Added session overview & implemented session join/leave.
PTS3-S34A/Soccar pull request #11
Opened 2016-10-03 14:23 UTC by bras1223

2016-10-03 18:11 UTC, Laugslander reviewed
Kleine verbeterpunten toegevoegd.

2016-10-03 18:11 UTC, Laugslander commented on Soccar [Client]/src/nl/soccar/library/Player.java
> +        return getUsername();
Het is netter om het field username te retourneren in plaats van de methode getUsername aan te roepen.

2016-10-03 18:11 UTC, Laugslander commented on Soccar [Client]/src/nl/soccar/library/Room.java
> -     * @param password
Beide parameters beschrijven.

2016-10-03 18:11 UTC, Laugslander commented on Soccar [Client]/src/nl/soccar/library/Room.java
> +     * @return
Returnwaarde beschrijven.

2016-10-03 18:11 UTC, Laugslander commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/SessionTableItem.java
> +        this.hostName = new SimpleStringProperty(new String("maatwerkException() thrown"));
Niet vergeten aan te passen voor iteratie 1. :)

2016-10-04 06:48 UTC, BeeHiveJava requested changes

2016-10-04 06:48 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/SessionTableItem.java
> +        if (s.getRoom().getHost() != null) {
s.getRoom().getHost() kan een lokale variabele worden -> Player host = s.getRoom().getHost(). Op die manier conserveer je wat ruimte voor de volgende statements. Ook kan host.getUsername() gebruikt worden i.p.v. toString().

2016-10-04 06:56 UTC, BeeHiveJava approved these changes

2016-10-04 06:56 UTC, merged