Game starten vanaf session view.
PTS3-S34A/Soccar pull request #30
Opened 2016-10-11 18:50 UTC by Laugslander

Game view geïmplementeerd en wijzigigen aangebracht in constants- en utilities-klassen zodat de game kan werken met verschillende schermresoluties. 

Het automatisch aanpassen van de game view op basis van de schermresolutie **moet nog worden geïmplementeerd**. 

Voor testdoeleinden worden de walls nog rood getekend. Dit moet uiteindelijk worden verwijderd.

Bij een aantal functies, klassen en constructoren is nog **documentatie vereist**.

2016-10-11 18:54 UTC, marcgroos commented on Soccar [Client]/src/nl/soccar/ui/DisplayConstants.java
> +    public static final float SCREEN_HEIGHT = 800;
TODO: Replace with the viewport resolution of the actual screen of the device in use.

2016-10-11 18:58 UTC, octotentakel approved these changes

2016-10-11 19:04 UTC, BeeHiveJava requested changes

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/DisplayConstants.java
> +    public static final float SCREEN_WIDTH = 1200;
1200**.0F**

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/DisplayConstants.java
> +    public static final float SCREEN_HEIGHT = 800;
800**.0F**

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/GameViewFXMLController.java
> +    AnchorPane anchorPane;
Encapsulation -> private.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/GameViewFXMLController.java
> +    Canvas canvas;
Encapsulation -> private.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +        float cornerSize = 15;
15**.0F

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +    public void addWalls() {
Moet deze methode persé public zijn? Ik vraag me af of hier een andere oplossing voor is.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/util/MapUtilities.java
> +    public static double getCentreX(Rectangle rectangle) {
Moet dit double zijn? We gebruiken nu overal float.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/util/MapUtilities.java
> +    public static double getCentreY(Rectangle rectangle) {
Moet dit double zijn? We gebruiken nu overal float.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/Main.java
> +    public void setFullScreen(boolean fullScreen) {
Deze methode mist documentatie.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/GameViewFXMLController.java
> +    public void initialize(URL url, ResourceBundle rb) {
Deze methode is overridden -> geen documentatie.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/SessionViewFXMLController.java
> +    public void startGame() {
Deze methode mist documentatie.

2016-10-11 19:04 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +    public void addWalls() {
Deze methode mist documentatie.

2016-10-11 19:16 UTC, BeeHiveJava requested changes

2016-10-11 19:16 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/controller/SessionViewFXMLController.java
> +        // btnStartGame.setDisable(occupancy != capacity);
Uncommenten of TODO toevoegen.

2016-10-12 05:38 UTC, Laugslander commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +    public void addWalls() {
Op dit moment worden de muren in GameViewFXMLController toegevoegd NA het aanmaken van het MapUiFx object zodat deze worden getekend boven de map.

2016-10-12 06:35 UTC, BeeHiveJava approved these changes

2016-10-12 06:35 UTC, merged