Physics update merge
PTS3-S34A/Soccar pull request #33
Opened 2016-10-14 11:32 UTC by marcgroos

Updates to the car physics, keyboard handling, visuals and added handbrake support.

2016-10-14 15:13 UTC, marcgroos commented on Soccar [Client]/src/nl/soccar/ui/physics/models/CarPhysics.java
> + * CarPhysics is a physics-model that keeps track of the physics of the Car.
In mijn IDE was de originele comment verdwenen dus deze verander ik weer terug naar "a Car".

2016-10-14 18:10 UTC, Ranray requested changes

2016-10-14 18:10 UTC, Ranray commented on Soccar [Client]/src/nl/soccar/ui/physics/models/WheelPhysics.java
> +    private float desiredSpeed = 0;
private float desiredSpeed = **0.0F**;

2016-10-15 07:53 UTC, BeeHiveJava requested changes
Mooie aanpassingen, een hoop is verbeterd. De nieuwe manier van keyboard input voor ik mooi, wel vraag ik me af of de acties niet efficiënter kunnen (Arrays.asList(..)).

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/models/CarUiFx.java
> +}
Newline invoegen.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/input/Keyboard.java
> +    private static List<KeyCode> PRESSED_KEYS;
Final list  - > constante.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/input/Keyboard.java
> +    private Keyboard() {
Constructor boven methodes  plaatsen.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/WorldObject.java
> +}
Newline invoegen.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +}
Newline invoegen.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/CarPhysics.java
> +}
Newline invoegen.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/WheelPhysics.java
> +        if (desiredSpeed < currentSpeed) force *= -1; // Negative force
Ook one-line statements gebruiken brackets.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/WheelPhysics.java
> +        if (desiredSpeed == currentSpeed) return; // Don't do anything
Zie comment hierboven.

2016-10-15 07:53 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/WheelPhysics.java
> +}
Newline invoegen.

2016-10-15 07:58 UTC, octotentakel commented on Soccar [Client]/src/nl/soccar/ui/input/Keyboard.java
> +    private static List<KeyCode> PRESSED_KEYS;
Die List is toch niet constant? Er worden steeds KeyCodes aan toegevoegd en verwijderd. Of kan je de List nog steeds aanpassen terwijl die final is?

2016-10-15 10:29 UTC, BeeHiveJava approved these changes

2016-10-15 10:32 UTC, Ranray approved these changes

2016-10-15 11:14 UTC, merged