JavaFX UI (FXML) Begin menu.
PTS3-S34A/Soccar pull request #5
Opened 2016-09-26 17:24 UTC by bras1223

2016-09-26 17:44 UTC, Ranray commented on Soccar [Client]/src/nl/soccar/ui/Main.java
> +            Scene scene = new Scene(root, 1200, 800);
Later aanpassen naar de standaard waarden

2016-09-26 17:48 UTC, Ranray commented on Soccar [Client]/src/nl/soccar/ui/MainMenuFXMLController.java
> +            Main.getInstance().setScene("CreateRoomFXML.fxml");
Magic waardes aanpassen in de volgende versie.

2016-09-26 17:50 UTC, Ranray approved these changes
Ziet er goed uit, alleen morgen nog paar magic waardes aanpassen en de standaard resolutie waardes toepassen.

2016-09-27 06:41 UTC, BeeHiveJava requested changes

2016-09-27 06:41 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/MainMenuFXMLController.java
> +    Button btnCreateRoom;
Encapsulatie (Private maken) van deze Button.

2016-09-27 06:58 UTC, BeeHiveJava approved these changes

2016-09-27 06:58 UTC, merged