Goal implementation
PTS3-S34A/Soccar pull request #50
Opened 2016-10-17 21:01 UTC by marcgroos

Fixes issue #43

2016-10-17 21:06 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Game.java
> +    public void setLastBallTouched(Player lastBallTouched) {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:06 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Game.java
> +    public Player getLastBallTouched() {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:07 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Game.java
> +    public void setStatus(GameStatus status) {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:07 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +public class Notification extends Entity {
Deze class moet nog goed worden gedocumenteerd.

2016-10-17 21:08 UTC, marcgroos commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +//    }
Vergeten te verwijderen.

2016-10-17 21:15 UTC, BeeHiveJava requested changes
Niet alles is even belangrijk, dus kijk maar wat je kunt fixen voor morgen.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +    }
Newline invoegen na deze methode.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/GameCanvas.java
> +    }
Newline invoegen na deze methode.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/GameCanvasFx.java
> +        if (status == GameStatus.SCORED) {
Beschrijven waarom dit kan (het is raar als je kijkt naar de vorige if-statement).

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +//    @Override
Deze comment moet weggehaald worden.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/fx/models/MapUiFx.java
> +    public void drawScoreboard(GraphicsContext context, Rectangle mapSize) {
Kan deze methode niet private zijn?

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/BallContactListener.java
> +            System.out.println(car.getPlayer().getUsername() + " has hit the ball!");
Deze s-out moet nog verwijderd worden.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/BallContactListener.java
> +    }
Newline invoegen na deze methode.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +    public void checkGoalScored() {
Kan deze methode niet private zijn?

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +            System.out.println("GOAL RED");
Deze s-out moet nog weggehaald worden.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +            System.out.println("GOAL BLUE");
Deze s-out moet nog weggehaald worden.

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +        float ballX = ball.getX();
Er wordt hier nooit op een Y-waarde gecontroleerd... is dit gewenst gedrag?

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +        if (ballX > 156.0F) {
Moet dit niet uit de goal-rectangle gehaald worden?

2016-10-17 21:15 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +        } else if (ballX < 4.0F) {
Moet dit niet uit de goal-rectangle gehaald worden?

2016-10-17 21:20 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +    public String getContent() {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:20 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +    public Font getFont() {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:20 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +    public Color getStroke() {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:20 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +    public Color getFill() {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:20 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/library/Notification.java
> +    public Notification(float x, float y, float degree, String content, Font font, Color fill, Color stroke) {
Deze constructor moet nog goed gedocumenteerd worden.

2016-10-17 21:22 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/GameCanvas.java
> +    public final void addWorldObject(WorldObject worldObject) {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-17 21:22 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/GameCanvas.java
> +    public final void removeWorldObject(WorldObject worldObject) {
Deze methode moet nog goed gedocumenteerd worden.

2016-10-18 06:25 UTC, marcgroos commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +        float ballX = ball.getX();
Ja

2016-10-18 07:09 UTC, BeeHiveJava requested changes

2016-10-18 07:09 UTC, BeeHiveJava commented on Soccar [Client]/src/nl/soccar/ui/physics/models/BallPhysics.java
> +        System.out.println(getX() + " " + getY());
Deze s-out weghalen.

2016-10-18 07:10 UTC, BeeHiveJava approved these changes

2016-10-18 07:10 UTC, merged